import { GTM_ID } from '@/lib/env'
import { GoogleTagManager } from '@next/third-parties/google'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" translate="no" suppressHydrationWarning>
      <GoogleTagManager gtmId={GTM_ID as string} />
      <body>{children}</body>
    </html>
  )
}
